site_name: KerasCustom
site_description: "Custom Layers and utilities for Keras 3"
site_author: "ducoffeM"
repo_url: https://github.com/ducoffeM/keras_custom
theme:
  name: material
  logo: images/logo.png # optional: add a small logo under docs/images
  favicon: images/favicon.ico

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Tutorials:
      - Model splitting: tutorials/model-splitting.md
      - Model switching: tutorials/model-switching.md
  - Reference:
      - API: reference/api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy # or google or napoleon-like
            rendering:
              show_root_toc_entry: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true

