name: "Build and deploy Github pages"

on:
  push:
    branches:
      - main # or your default branch

permissions:
  contents: write # needed to push to gh-pages
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mike mkdocstrings[python]
          # install your package in editable mode so mkdocstrings can import it:
          pip install -e .

      - name: "Setup Docs Deploy"
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: "Deploy Github Pages"
        run: |
          mike deploy --push --update-aliases ${{ github.event.release.tag_name }} latest
          mike set-default --push latest
